export default {
  '0480b142': [() => import(/* webpackChunkName: '0480b142' */ '@site/docs/faq.md'), '@site/docs/faq.md', require.resolveWeak('@site/docs/faq.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '2450daf5': [() => import(/* webpackChunkName: '2450daf5' */ '@site/docs/data-management.md'), '@site/docs/data-management.md', require.resolveWeak('@site/docs/data-management.md')],
  '27403e02': [() => import(/* webpackChunkName: '27403e02' */ '@site/docs/ingestion.md'), '@site/docs/ingestion.md', require.resolveWeak('@site/docs/ingestion.md')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '3b8c55ea': [() => import(/* webpackChunkName: '3b8c55ea' */ '@site/docs/installation.md'), '@site/docs/installation.md', require.resolveWeak('@site/docs/installation.md')],
  '8418c612': [() => import(/* webpackChunkName: '8418c612' */ '@site/docs/query.md'), '@site/docs/query.md', require.resolveWeak('@site/docs/query.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  '99c4ee56': [() => import(/* webpackChunkName: '99c4ee56' */ '/Users/sonamgupta/git-local/github-pages-docusaurus/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/Users/sonamgupta/git-local/github-pages-docusaurus/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/sonamgupta/git-local/github-pages-docusaurus/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],
  'b4caa8c6': [() => import(/* webpackChunkName: 'b4caa8c6' */ '/Users/sonamgupta/git-local/github-pages-docusaurus/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/Users/sonamgupta/git-local/github-pages-docusaurus/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/Users/sonamgupta/git-local/github-pages-docusaurus/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  'fece9508': [() => import(/* webpackChunkName: 'fece9508' */ '@site/docs/integrations.md'), '@site/docs/integrations.md', require.resolveWeak('@site/docs/integrations.md')],};
